// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/iakovosvo/go-htmx-contacts-app/services"

func Form(formData services.FormData) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"contact-form\" class=\" p-6 bg-sky-950 rounded-lg shadow-md\" hx-post=\"/contacts\" hx-swap=\"outerHTML\"><div class=\"mb-6\"><label for=\"firstName\" class=\"block mb-2 text-lg font-bold text-white\">First Name</label> <input type=\"text\" name=\"firstName\" id=\"firstName\" placeholder=\"Enter first name\" class=\"bg-inherit border border-gray-300  text-white text-sm rounded-lg focus:outline-none focus:border-sky-700 focus:ring-1 focus:ring-sky-700 block w-full p-2.5\"></div><div class=\"mb-6\"><label for=\"lastName\" class=\"block mb-2 text-lg font-bold text-white\">Last Name</label> <input type=\"text\" name=\"lastName\" id=\"lastName\" placeholder=\"Enter last Name\" class=\"bg-inherit border border-gray-300  text-white text-sm rounded-lg focus:outline-none focus:border-sky-700 focus:ring-1 focus:ring-sky-700 block w-full p-2.5\"></div><div class=\"mb-6\"><label for=\"email\" class=\"block mb-2 text-lg font-bold text-white\">Email</label> <input type=\"email\" name=\"email\" id=\"email\" placeholder=\"Email\" class=\"bg-inherit border border-gray-300 text-gray-900 text-sm rounded-lg focus:outline-none focus:border-sky-700 focus:ring-1 focus:ring-sky-700 block w-full p-2.5\"></div><button type=\"submit\" class=\"w-full text-sky-950 bg-white focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-2xl text-lg px-5 py-2.5 text-center\">Add</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
